/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package condicionescompetencias;

/**
 *
 * @author jeans
 */
public class CondicionesCompetencias extends javax.swing.JFrame {

      private Hilo t1;
        private Hilo t2;
        private Hilo t3;
        private Hilo t4;
        private Rcompartido rc;
        private Mute_x mx;
        //private dekker dek;
        private cerradura cr; //para cerradura
        public static boolean piter;
        public static boolean cond;
        public static boolean intre;
        public static boolean dekk;
        public static boolean dijk;
        public static boolean mute;
        public static boolean m;
    public CondicionesCompetencias() {
        initComponents();
        mx= new Mute_x(m);
        cr = new cerradura();
        rc = new Rcompartido();
        t1 = new Hilo(area1,rc,cr,mx);
        t1.setName("perrito1");
        t2= new Hilo(area2,rc,cr,mx);
        t2.setName("perrito2");
        t3= new Hilo(area3,rc,cr,mx);
        t3.setName("perrito3");
        t4= new Hilo(area4,rc,cr,mx);
        t4.setName("perrito4");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        area2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        area3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        area4 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        condiciones = new javax.swing.JRadioButtonMenuItem();
        petterson = new javax.swing.JRadioButtonMenuItem();
        interrupcioneh = new javax.swing.JRadioButtonMenuItem();
        dekker = new javax.swing.JRadioButtonMenuItem();
        dijkstra = new javax.swing.JRadioButtonMenuItem();
        mutex = new javax.swing.JRadioButtonMenuItem();

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jButton3.setText("pausar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("detener");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        area1.setEditable(false);
        area1.setColumns(20);
        area1.setRows(5);
        jScrollPane1.setViewportView(area1);

        area2.setEditable(false);
        area2.setColumns(20);
        area2.setRows(5);
        jScrollPane2.setViewportView(area2);

        area3.setEditable(false);
        area3.setColumns(20);
        area3.setRows(5);
        jScrollPane3.setViewportView(area3);

        area4.setEditable(false);
        area4.setColumns(20);
        area4.setRows(5);
        jScrollPane4.setViewportView(area4);

        jLabel1.setText("hilo 1");

        jLabel2.setText("hilo 2");

        jLabel3.setText("hilo 3");

        jLabel4.setText("hilo 4");

        jMenu1.setText("opciones");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Algoritmos");

        buttonGroup1.add(condiciones);
        condiciones.setSelected(true);
        condiciones.setText("Condiciones Competencias");
        condiciones.setActionCommand("CondicionesCompetencias");
        jMenu2.add(condiciones);
        condiciones.getAccessibleContext().setAccessibleName("CondicionesCompetencias");

        buttonGroup1.add(petterson);
        petterson.setActionCommand("Petterson");
        petterson.setLabel("Petterson");
        petterson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pettersonActionPerformed(evt);
            }
        });
        jMenu2.add(petterson);

        buttonGroup1.add(interrupcioneh);
        interrupcioneh.setText("Desactivacion de interrupciones");
        jMenu2.add(interrupcioneh);

        buttonGroup1.add(dekker);
        dekker.setText("Dekker");
        jMenu2.add(dekker);

        buttonGroup1.add(dijkstra);
        dijkstra.setText("Dijkstra");
        jMenu2.add(dijkstra);

        buttonGroup1.add(mutex);
        mutex.setText("Mutex");
        jMenu2.add(mutex);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cond=false; 
        piter=false;
        intre=false;
        dijk=false;
        dekk=false;
        mute=false;
       //------------condiciones (sin algoritmo)------------------
        if(condiciones.isSelected()){   
        System.out.println(cond);
        System.out.println("cond");
        cond=true;
        t1.start();
        t2.start();
        t3.start();
        t4.start();
        }
        //----------------cerradura (sin exclusion mutua)-------------------
        else if(petterson.isSelected()){
        piter=true;
        System.out.println(piter);
        System.out.println("piter");
         t1.start();
        t2.start();
        t3.start();
        t4.start();
        }
        //------------dessact de interrupciones (sin exclusion mutua)----------------------
        else if(interrupcioneh.isSelected()){
        intre=true;
        System.out.println(intre);
        System.out.println("intre");
        t1.start();
        t2.start();
        t3.start();
        t4.start();
        }
        //------------dekker  (exclusion mutua)-------------------------
          else if(dekker.isSelected()){
        dekk=true;
        System.out.println(dekk);
        System.out.println("dekk");
         t1.start();
        t2.start();
        t3.start();
        t4.start();
          //------------dijstra(exclusion mutua)------------------------
        }    else if(dijkstra.isSelected()){
        dijk=true;
        System.out.println(dijk);
        System.out.println("dijk");
         t1.start();
        t2.start();
        t3.start();
        t4.start();
        }
        //------------mutex  (exclusion mutua)-------------------------
           else if(mutex.isSelected()){
        mute=true;
        System.out.println(mute);
        System.out.println("mute");
        t1.start();
        t2.start();
        t3.start();
        t4.start();
        }
        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int HiloRand=(int)(Math.random()*4);
        System.out.println("se va a morir el perrito "+ (HiloRand+1));
        switch(HiloRand){
            case 0:
                try{
                   
                    t1.setDead(true);
                }catch(Exception e){e.printStackTrace();}
                break;
            case 1:
                 try{
                    t2.setDead(true);
                }catch(Exception e){e.printStackTrace();}
                 break;
            case 2:
                 try{
                    t3.setDead(true);
                }catch(Exception e){e.printStackTrace();}
                 break;
            case 3:
                 try{
                    t4.setDead(true);
                }catch(Exception e){e.printStackTrace();}
                 break;
            default:break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pettersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pettersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pettersonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CondicionesCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CondicionesCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CondicionesCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CondicionesCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CondicionesCompetencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JTextArea area2;
    private javax.swing.JTextArea area3;
    private javax.swing.JTextArea area4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButtonMenuItem condiciones;
    private javax.swing.JRadioButtonMenuItem dekker;
    private javax.swing.JRadioButtonMenuItem dijkstra;
    private javax.swing.JRadioButtonMenuItem interrupcioneh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButtonMenuItem mutex;
    private javax.swing.JRadioButtonMenuItem petterson;
    // End of variables declaration//GEN-END:variables

}
